namespace FoundryAgent.Web.Models;

/// <summary>
/// Response model for chat interactions with the agent.
/// </summary>
public class ChatResponse
{
    /// <summary>
    /// The agent's response text.
    /// </summary>
    public string Response { get; set; } = string.Empty;

    /// <summary>
    /// The thread ID for continuing the conversation.
    /// </summary>
    public string? ThreadId { get; set; }

    /// <summary>
    /// The agent ID that processed the request.
    /// </summary>
    public string? AgentId { get; set; }

    /// <summary>
    /// The run ID for this interaction.
    /// </summary>
    public string? RunId { get; set; }

    /// <summary>
    /// Tool calls made during this interaction.
    /// </summary>
    public List<ToolCallInfo>? ToolCalls { get; set; }

    /// <summary>
    /// Telemetry trace ID for observability.
    /// </summary>
    public string? TraceId { get; set; }

    /// <summary>
    /// File references generated by the agent (e.g., from Code Interpreter).
    /// </summary>
    public List<FileReference>? GeneratedFiles { get; set; }

    /// <summary>
    /// Citations from grounding sources (Bing, AI Search).
    /// </summary>
    public List<Citation>? Citations { get; set; }
}

/// <summary>
/// Information about a tool call made by the agent.
/// </summary>
public class ToolCallInfo
{
    public string Name { get; set; } = string.Empty;
    public string Arguments { get; set; } = string.Empty;
    public string? Output { get; set; }
}

/// <summary>
/// Reference to a file generated by the agent.
/// </summary>
public class FileReference
{
    public string FileId { get; set; } = string.Empty;
    public string? FileName { get; set; }
    public string? MimeType { get; set; }
}

/// <summary>
/// Citation from grounding sources.
/// </summary>
public class Citation
{
    public string Title { get; set; } = string.Empty;
    public string? Url { get; set; }
    public string? Content { get; set; }
}
